### ISSUE TITLE
咋个报错呀

### ISSUE THREAD

**Issue by aaq1adqwe** [dpu/coremail-address-book#1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x643bf3]

goroutine 1 [running]:
main.getResp(0xc0000e0000, 0x69, 0x0, 0x1, 0xc00008c090, 0x29, 0x0, 0x0)
        C:/Users/xxx/Desktop/coremail-address-book-windows-amd64/main.go:77 +0x423
main.main()
        C:/Users/xxx/Desktop/coremail-address-book-windows-amd64/main.go:30 +0x1cb

**Comment by xu42** [comment]
@leaderzhang 没有在Windows平台测试过，建议使用二进制包。

**Comment by aaq1adqwe** [comment]
> @leaderzhang 没有在Windows平台测试过，建议使用二进制包。

二进制包也是这样报错。。。。

**Comment by xu42** [comment]
@leaderzhang 你执行的完整命令及报错，贴一下，谢谢。

**Comment by hktalent** [comment]
me too, mac os:

./main -coremail_cookie "Coremail=xxxxxx" -coremail_sid xxxxx -host xxxx

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1262605]

goroutine 1 [running]:
main.getResp(0xc000102120, 0x5d, 0x0, 0x1, 0xc00016a0c0, 0xb8, 0x0, 0x0)
	main.go:77 +0x435
main.main()
	/main.go:30 +0x1d4

**Comment by xu42** [comment]
@hktalent 

```bash
./main -coremail_cookie xxx -coremail_sid xxx
```

`-coremail_cookie` params not contain `Coremail=`, just `xxxxx`

**Comment by hktalent** [comment]
```
 ./main -coremail_cookie 210a305aa243845f4xx -coremail_sid "xx" -host xxx:443 -protocol https

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12626b5]

goroutine 1 [running]:
main.getResp(0xc0000200e0, 0x61, 0x0, 0x1, 0xc000016180, 0x29, 0x0, 0x0)
	main.go:79 +0x435
main.main()
	/main.go:32 +0x1ec
```

**Comment by xu42** [comment]
@hktalent 
```bash
-host xxx
```

`-host` params not contain `:443`, just xxx

**Comment by hktalent** [comment]
@xu42 
same
````
./main -coremail_cookie 210a305aa243845f46594xx -coremail_sid BAvnunOOinRfMochxxv -host 125xx20 -protocol https

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12626b5]

goroutine 1 [running]:
main.getResp(0xc0000241e0, 0x5d, 0x0, 0x1, 0xc000016180, 0x29, 0x0, 0x0)
	/main.go:79 +0x435
main.main()
	main.go:32 +0x1ec
```

**Comment by xu42** [comment]
@hktalent your host is ip? not domain?

**Comment by hktalent** [comment]
@xu42 is is ip
error is here:
defer resp.Body.Close()

**Comment by xu42** [comment]
@hktalent
ip not suport https,please try again.
```bash
./main -coremail_cookie 210a305aa243845f46594xx -coremail_sid BAvnunOOinRfMochxxv -host 125.x.x.20
```

**Comment by hktalent** [comment]
@xu42 same

**Comment by xu42** [comment]
@hktalent Sorry, the same program is currently normal on my macOS. May be related to go version or coremail version, I don't have the exact same environment to test.

```bash
go version go1.14.2 darwin/amd64
macOS 10.14.3
coremail unknown
```

**Comment by hktalent** [comment]
@xu42 thanks for you
